import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <Link href="/meow" className={styles.card}>
            <a className={styles.card}>Meow</a>
          </Link>
          <Link href="/posts" className={styles.card}>
            <a className={styles.card}>Posts</a>
          </Link>
          <Link href="/hello" className={styles.card}>
            <a className={styles.card}>Hello</a>
          </Link>

          <Link href="/products/1" className={styles.card}>
            <a className={styles.card}>Dynamic Product</a>
          </Link>

          <Link href="/blog/1" className={styles.card}>
            <a className={styles.card}>Dynamic Blog</a>
          </Link>

          <Link href="/posts/1" className={styles.card}>
            <a className={styles.card}>Dynamic Posts</a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
